---
AWSTemplateFormatVersion: '2010-09-09'
Description: Creates S3 bucket to contain ELB logging records for a given environment.
Parameters:
  Environment:
    Description: Application Environment
    Type: String
    Default: dv
    AllowedValues:
      - dv
      - qa
      - pt
      - st
      - pr
  EC2InstanceType:
    Type: String
  EC2AMI:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  KeyName:
    Type: String
  PublicSubnet:
    Type: String
Resources:

  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:
        !Sub 'Security group for ${AWS::StackName} bastion host'
      VpcId: !Ref VPC

  BastionInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref EC2AMI
      InstanceType: !Ref EC2InstanceType
      KeyName: !Ref KeyName
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref BastionSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-BastionInstance'


  BastionAllowInboundSSHFromInternet:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref BastionSecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      CidrIp: 0.0.0.0/0

  BastionAllowOutboundSSHToApplication:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref BastionSecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      DestinationSecurityGroupId: !Ref ApplicationSecurityGroup




#  STACK_NAME=bastion-poc
#  REGION=us-east-1
#  CLI_PROFILE=your-aws-profile-with-an-appropiate-role
#  EC2_INSTANCE_TYPE=t2.micro
#  KEY_NAME=your-key-pair-name
#
#  # Deploy the CloudFormation template
#  echo -e "\n\n=========== Deploying main.yml ==========="
#  aws cloudformation deploy --region $REGION \
#  --profile $CLI_PROFILE \
#  --stack-name $STACK_NAME \
#  --template-file main.yml \
#  --no-fail-on-empty-changeset \
#  --capabilities CAPABILITY_NAMED_IAM \
#  --parameter-overrides \
#  EC2InstanceType=$EC2_INSTANCE_TYPE \
#  KeyName=$KEY_NAME
#
#  # If the deploy succeeded, show the instances' IP address
#  if [ $? -eq 0 ]; then
#  aws cloudformation list-exports \
#  --profile $CLI_PROFILE \
#  --region $REGION \
#  --query "Exports[?ends_with(Name,'Ip')].Value"
#  fi