AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Environment:
    Type: String
    Default: dv
    AllowedValues:
      - dv
      - qa
      - pt
      - st
      - pr
  ProjectId:
    Description: ProjectId = Project + environment
    Type: String
  BucketName:
    Description: Name of Resource Bucket
    Type: String
Resources:
  StudioResourceBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BucketName
      Tags:
        - Key: Name
          Value: !Join
            - '-'
            - - !Ref ProjectId
              - credentials-bucket
        - Key: Environment
          Value: !Ref Environment
  CredentialAccessorPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: Policy for accessing these credentials
      Path: !Join
        - ''
        - - /
          - !Ref Environment
          - credentials/access/
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
              - 's3:GetObjectVersion'
              - 's3:ListBucket'
              - 's3:ListBucketVersions'
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref BucketName
                  - /*
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref BucketName
  CredentialModifierPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: Policy for modifying these credentials
      Path: !Join
        - ''
        - - /
          - !Ref Environment
          - /credentials/modify/
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:PutObject'
              - 's3:DeleteObject'
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref BucketName
                  - /*
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref BucketName
