project         : "ccd"
env             : "dv"
project_id      : "{{ project }}-{{ env }}"
region          : "us-east-2"
#key_name: "{{ env }}_keypair_{{ region }}"
#key_name: "{{ project_id }}_keypair_{{ region }}"
#key_name: "ansible_tutorial"
key_name        : ccd-dv_keypair_us-east-2

aws_account     : 793628107353
#ecr_endpoint   : 793628107353.dkr.ecr.us-east-1.amazonaws.com

domain          : cdd.net
tm_domain       : cdd.com
stm_domain      : cdd.com
app_name        : "app-{{ project_id }}"
svc_name        : "svc-{{ project_id }}"
cdn_name        : "cdn-{{ project_id }}"