#server:
#  port: 8080
#management.endpoints.web.exposure.include: "*"
#management.endpoint.shutdown.enabled: true
#
#spring:
#  security:
#    user:
#      roles     : ENDPOINT_ADMIN
#      name      : admin
#      password  : admin