---
- hosts                       : localhost
  connection                  : local
  gather_facts                : no
  vars_files:
    - "inventory/group_vars/{{ env }}/config.yml"
    #- "inventory/group_vars/{{ env }}/secrets.yml"
  environment:
    AWS_DEFAULT_REGION        : "{{ region }}"
  vars:
  tasks:
    - name                    : "CREATE STACK: {{ credentials_bucket_stack_name }} "
      cloudformation:
        stack_name            : "{{ credentials_bucket_stack_name }}"
        state                 : "present"
        region                : "{{ region }}"
        template              : "templates/credentials-bucket.yml"
        template_parameters:
          Environment         : "{{ env }}"
          ProjectId           : "{{ project_id }}"
          BucketName          : "{{ credentials_bucket_name }}"
      register: credentials_bucket
    - debug: msg="log_bucket:{{ credentials_bucket.stack_outputs }}"

