---
- hosts                       : localhost
  connection                  : local
  gather_facts                : no
  vars_files:
    - "inventory/group_vars/{{ env }}/config.yml"
    #- "inventory/group_vars/{{ env }}/secrets.yml"
  environment:
    AWS_DEFAULT_REGION        : "{{ region }}"
  vars:
  tasks:
    - name                    : "CREATE STACK: {{ cluster_stack_name }} "
      cloudformation:
        stack_name            : "{{ cluster_stack_name }}"
        state                 : "present"
        region                : "{{ region }}"
        template              : "templates/database-cluster.yml"
        template_parameters:
#          Environment         : "{{ env }}"
#          ProjectId           : "{{ project_id }}"
#          DBName              : "{{ config.db_name }}"
          DBUsername          : "{{ config.db_username }}"
          DBPassword          : "{{ config.db_password }}"


      register: cluster
    - name: show {{ database_stack_name }} stack outputs
      debug: msg="Created {{ database_stack_name }} created with these resources {{ database.stack_outputs }}"



