---
- hosts                       : localhost
  connection                  : local
  gather_facts                : no
  vars_files:
    - "inventory/group_vars/{{ env }}/config.yml"
    #- "inventory/group_vars/{{ env }}/secrets.yml"
  environment:
    AWS_DEFAULT_REGION        : "{{ region }}"
  vars:
  tasks:
  - cloudformation_facts:
      all_facts: false
    register: vpc_stack
  - set_fact:
      vpc: "{{ vpc_stack.ansible_facts.cloudformation[vpc_stack_name].stack_outputs }}"

    #- debug                   : msg="{{ keyname }}"
  - name                    : "CREATE STACK: {{ consul_stack_name }} "
    cloudformation:
      stack_name            : "{{ consul_stack_name }}"
      state                 : "present"
      region                : "{{ region }}"
      template              : "templates/consul.yml"
      template_parameters:
        Environment         : "{{ env }}"
        ProjectId           : "{{ project_id }}"
        VPC                 : "{{ vpc.VpcId }}"
        VpcCidr             : "{{ vpc.VpcCidr }}"
        AvailabilityZone1   : "{{ vpc.AvailabilityZone1 }}"
        AvailabilityZone2   : "{{ vpc.AvailabilityZone2 }}"
        PrivateRouteTable1  : "{{ vpc.PrivateRouteTable1 }}"
        PrivateRouteTable2  : "{{ vpc.PrivateRouteTable2 }}"
        BastionSecurityGroup: "{{ vpc.BastionSecurityGroup }}"
        ConsulSubnet1Cidr   : "{{ consul_subnet_1_cidr }}"
        ConsulSubnet2Cidr   : "{{ consul_subnet_2_cidr }}"
        InstanceType        : "{{ consul_instance_type }}"
        InstanceCount       : "{{ consul_server_count }}"
        KeyName             : "{{ key_name }}"
        ConsulAMI           : "{{ consul_ami }}"

#  - name: show consul stack outputs
#    debug: msg="Created {{ consul_stack_name }} with {{ consul.stack_outputs }}"
