spring:
  application:
    name: my-api
  profiles:
    active: test

---
spring:
  profiles: itest
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:4306/my-api?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root_password